name: Deploy Static Site to EC2 (Self-Hosted Runner + NGINX)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Prepare Static Files
      run: |
        rm -rf deploy
        mkdir deploy
        cp index.html deploy/
        cp onboarding.js deploy/
        cp test.js deploy/
        ls -l deploy

    - name: Print URL
      run: echo "Site Live:Success"
